/* Generated By:JavaCC: Do not edit this line. UQLParserConstants.java */
package com.demo.stage1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int MOVIE = 7;
  /** RegularExpression Id. */
  int ACTOR = 8;
  /** RegularExpression Id. */
  int DIRECTOR = 9;
  /** RegularExpression Id. */
  int KEYWORD = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int EQUALS = 13;
  /** RegularExpression Id. */
  int NOTEQUAL = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int QUOTED_STRING = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"and\"",
    "\"or\"",
    "\"title\"",
    "\"actor\"",
    "\"director\"",
    "\"keyword\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "<STRING>",
    "<QUOTED_STRING>",
  };

}
