//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.22 at 02:57:06 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.release3.com/rules", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.release3.transform.rules.model;
