//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.16 at 11:04:48 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.release3.com/ProgramUnitGen", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.release3.programunitgen;
