/*******************************************************************************
 * Copyright (c) 2009, 2013 ObanSoft Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Jayansh Shinde
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.16 at 11:04:48 AM IST 
//


package com.release3.programunitgen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.oracle.xmlns.forms.ProgramUnit;


/**
 * <p>Java class for R3ProgramUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="R3ProgramUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="R3ProgramUnit" type="{http://xmlns.oracle.com/Forms}ProgramUnit" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="toBeMigrate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MoveToDB" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="JavaMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "R3ProgramUnit", propOrder = {
    "r3ProgramUnit"
})
public class R3ProgramUnit {

    @XmlElement(name = "R3ProgramUnit")
    protected ProgramUnit r3ProgramUnit;
    @XmlAttribute(name = "toBeMigrate")
    protected Boolean toBeMigrate;
    @XmlAttribute(name = "MoveToDB")
    protected Boolean moveToDB;
    @XmlAttribute(name = "JavaMethod")
    protected String javaMethod;

    /**
     * Gets the value of the r3ProgramUnit property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramUnit }
     *     
     */
    public ProgramUnit getR3ProgramUnit() {
        return r3ProgramUnit;
    }

    /**
     * Sets the value of the r3ProgramUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramUnit }
     *     
     */
    public void setR3ProgramUnit(ProgramUnit value) {
        this.r3ProgramUnit = value;
    }

    /**
     * Gets the value of the toBeMigrate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToBeMigrate() {
        return toBeMigrate;
    }

    /**
     * Sets the value of the toBeMigrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToBeMigrate(Boolean value) {
        this.toBeMigrate = value;
    }

    /**
     * Gets the value of the moveToDB property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMoveToDB() {
        return moveToDB;
    }

    /**
     * Sets the value of the moveToDB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMoveToDB(Boolean value) {
        this.moveToDB = value;
    }

    /**
     * Gets the value of the javaMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaMethod() {
        return javaMethod;
    }

    /**
     * Sets the value of the javaMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaMethod(String value) {
        this.javaMethod = value;
    }

}
