/*******************************************************************************
 * Copyright (c) 2009, 2013 ObanSoft Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Jayansh Shinde
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 10:07:58 PM IST 
//


package com.release3.customization;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.release3.customization.blockcust.BlockCustType;
import com.release3.customization.builtin.BuiltinType;
import com.release3.customization.parameter.ParameterType;
import com.release3.customization.recordgroup.RecordGroupType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Trigger" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Parameter" type="{http://www.release3.com/Customization/Parameter}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Builtin" type="{http://www.release3.com/Customization/Builtin}BuiltinType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Refresh" type="{http://www.release3.com/Customization}RefreshType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Block" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Item" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Jsfattr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="plsql" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MethodType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RecordGroup" type="{http://www.release3.com/Customization/RecordGroup}RecordGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BlockCust" type="{http://www.release3.com/Customization/BlockCust}BlockCustType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trigger",
    "recordGroup",
    "blockCust"
})
@XmlRootElement(name = "R3")
public class R3 {

    @XmlElement(name = "Trigger")
    protected List<R3 .Trigger> trigger;
    @XmlElement(name = "RecordGroup")
    protected List<RecordGroupType> recordGroup;
    @XmlElement(name = "BlockCust")
    protected List<BlockCustType> blockCust;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the trigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrigger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link R3 .Trigger }
     * 
     * 
     */
    public List<R3 .Trigger> getTrigger() {
        if (trigger == null) {
            trigger = new ArrayList<R3 .Trigger>();
        }
        return this.trigger;
    }

    /**
     * Gets the value of the recordGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecordGroupType }
     * 
     * 
     */
    public List<RecordGroupType> getRecordGroup() {
        if (recordGroup == null) {
            recordGroup = new ArrayList<RecordGroupType>();
        }
        return this.recordGroup;
    }

    /**
     * Gets the value of the blockCust property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blockCust property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlockCust().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlockCustType }
     * 
     * 
     */
    public List<BlockCustType> getBlockCust() {
        if (blockCust == null) {
            blockCust = new ArrayList<BlockCustType>();
        }
        return this.blockCust;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Parameter" type="{http://www.release3.com/Customization/Parameter}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Builtin" type="{http://www.release3.com/Customization/Builtin}BuiltinType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Refresh" type="{http://www.release3.com/Customization}RefreshType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Block" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Item" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Jsfattr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="plsql" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MethodType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter",
        "builtin",
        "refresh"
    })
    public static class Trigger {

        @XmlElement(name = "Parameter")
        protected List<ParameterType> parameter;
        @XmlElement(name = "Builtin")
        protected List<BuiltinType> builtin;
        @XmlElement(name = "Refresh")
        protected List<RefreshType> refresh;
        @XmlAttribute(name = "Block")
        protected String block;
        @XmlAttribute(name = "Item")
        protected String item;
        @XmlAttribute(name = "Jsfattr")
        protected String jsfattr;
        @XmlAttribute(name = "plsql")
        protected String plsql;
        @XmlAttribute(name = "MethodType")
        protected String methodType;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParameterType }
         * 
         * 
         */
        public List<ParameterType> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<ParameterType>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the builtin property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the builtin property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBuiltin().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BuiltinType }
         * 
         * 
         */
        public List<BuiltinType> getBuiltin() {
            if (builtin == null) {
                builtin = new ArrayList<BuiltinType>();
            }
            return this.builtin;
        }

        /**
         * Gets the value of the refresh property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the refresh property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRefresh().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RefreshType }
         * 
         * 
         */
        public List<RefreshType> getRefresh() {
            if (refresh == null) {
                refresh = new ArrayList<RefreshType>();
            }
            return this.refresh;
        }

        /**
         * Gets the value of the block property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlock() {
            return block;
        }

        /**
         * Sets the value of the block property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlock(String value) {
            this.block = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the jsfattr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsfattr() {
            return jsfattr;
        }

        /**
         * Sets the value of the jsfattr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsfattr(String value) {
            this.jsfattr = value;
        }

        /**
         * Gets the value of the plsql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlsql() {
            return plsql;
        }

        /**
         * Sets the value of the plsql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlsql(String value) {
            this.plsql = value;
        }

        /**
         * Gets the value of the methodType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMethodType() {
            return methodType;
        }

        /**
         * Sets the value of the methodType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMethodType(String value) {
            this.methodType = value;
        }

    }

}
