/*******************************************************************************
 * Copyright (c) 2009, 2013 ObanSoft Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Jayansh Shinde
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.28 at 07:27:29 PM IST 
//


package com.release3.r3builtin.propertymap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.release3.r3builtin.propertymap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.release3.r3builtin.propertymap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link R3BuiltinsPropertyMap }
     * 
     */
    public R3BuiltinsPropertyMap createR3BuiltinsPropertyMap() {
        return new R3BuiltinsPropertyMap();
    }

    /**
     * Create an instance of {@link R3BuiltinsPropertyMap.PropertyMap }
     * 
     */
    public R3BuiltinsPropertyMap.PropertyMap createR3BuiltinsPropertyMapPropertyMap() {
        return new R3BuiltinsPropertyMap.PropertyMap();
    }

}
