//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.28 at 07:27:29 PM IST 
//


package com.release3.r3builtin.propertymap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyMap" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FormProperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JavaProperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JavaDataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyMap"
})
@XmlRootElement(name = "R3BuiltinsPropertyMap")
public class R3BuiltinsPropertyMap {

    @XmlElement(name = "PropertyMap")
    protected List<R3BuiltinsPropertyMap.PropertyMap> propertyMap;

    /**
     * Gets the value of the propertyMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propertyMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link R3BuiltinsPropertyMap.PropertyMap }
     * 
     * 
     */
    public List<R3BuiltinsPropertyMap.PropertyMap> getPropertyMap() {
        if (propertyMap == null) {
            propertyMap = new ArrayList<R3BuiltinsPropertyMap.PropertyMap>();
        }
        return this.propertyMap;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FormProperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JavaProperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JavaDataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "formProperty",
        "javaProperty",
        "javaDataType"
    })
    public static class PropertyMap {

        @XmlElement(name = "FormProperty", required = true)
        protected String formProperty;
        @XmlElement(name = "JavaProperty", required = true)
        protected String javaProperty;
        @XmlElement(name = "JavaDataType", required = true)
        protected String javaDataType;

        /**
         * Gets the value of the formProperty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormProperty() {
            return formProperty;
        }

        /**
         * Sets the value of the formProperty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormProperty(String value) {
            this.formProperty = value;
        }

        /**
         * Gets the value of the javaProperty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJavaProperty() {
            return javaProperty;
        }

        /**
         * Sets the value of the javaProperty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJavaProperty(String value) {
            this.javaProperty = value;
        }

        /**
         * Gets the value of the javaDataType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJavaDataType() {
            return javaDataType;
        }

        /**
         * Sets the value of the javaDataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJavaDataType(String value) {
            this.javaDataType = value;
        }

    }

}
