/* Generated By:JavaCC: Do not edit this line. FormsPlSqlJTreeTreeConstants.java Version 5.0 */
package com.release3.tf;

public interface FormsPlSqlJTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTGETCOMPILATIONUNITS = 1;
  public int JJTGETCOMPILATIONUNIT = 2;
  public int JJTDECLARATIONSECTION = 3;
  public int JJTDECLARATIONS = 4;
  public int JJTIDENTIFIERDECLARATION = 5;
  public int JJTCURSORDECLARATION = 6;
  public int JJTPROCEDUREDECLARATION = 7;
  public int JJTPROCEDUREBODY = 8;
  public int JJTFUNCTIONDECLARATION = 9;
  public int JJTFUNCTIONBODY = 10;
  public int JJTPRAGMADECLARATION = 11;
  public int JJTVARIABLEDECLARATION = 12;
  public int JJTCONSTANTDECLARATION = 13;
  public int JJTTYPEDECLARATION = 14;
  public int JJTBASICDATATYPEDECLARATION = 15;
  public int JJTEXCEPTIONDECLARATION = 16;
  public int JJTBEGINENDBLOCK = 17;
  public int JJTSEQUENCEOFSTATEMENTS = 18;
  public int JJTEXCEPTIONBLOCK = 19;
  public int JJTEXCEPTIONHANDLER = 20;
  public int JJTPLSQLSTATEMENT = 21;
  public int JJTLABELDECLARATION = 22;
  public int JJTSQLSTATEMENT = 23;
  public int JJTSUBROUTINECALL = 24;
  public int JJTASSIGNMENTSTATEMENT = 25;
  public int JJTEXITSTATEMENT = 26;
  public int JJTGOTOSTATEMENT = 27;
  public int JJTIFSTATEMENT = 28;
  public int JJTLOOPSTATEMENT = 29;
  public int JJTNORMALLOOP = 30;
  public int JJTWHILELOOP = 31;
  public int JJTFORLOOP = 32;
  public int JJTNUMERICFORLOOPLOOKAHEAD = 33;
  public int JJTNUMERICFORLOOP = 34;
  public int JJTCURSORFORLOOP = 35;
  public int JJTNULLSTATEMENT = 36;
  public int JJTRAISESTATEMENT = 37;
  public int JJTRETURNSTATEMENT = 38;
  public int JJTCLOSESTATEMENT = 39;
  public int JJTCOMMITSTATEMENT = 40;
  public int JJTFETCHSTATEMENT = 41;
  public int JJTLOCKTABLESTATEMENT = 42;
  public int JJTOPENSTATEMENT = 43;
  public int JJTROLLBACKSTATEMENT = 44;
  public int JJTSETTRANSACTIONSTATEMENT = 45;
  public int JJTLOCKMODE = 46;
  public int JJTSAVEPOINTSTATEMENT = 47;
  public int JJTUPDATESTATEMENT = 48;
  public int JJTCOLUMNVALUES = 49;
  public int JJTUPDATEDVALUE = 50;
  public int JJTINSERTSTATEMENT = 51;
  public int JJTDELETESTATEMENT = 52;
  public int JJTQUERYSTATEMENT = 53;
  public int JJTPLSQLEXPRESSION = 54;
  public int JJTPLSQLANDEXPRESSION = 55;
  public int JJTPLSQLUNARYLOGICALEXPRESSION = 56;
  public int JJTPLSQLRELATIONALEXPRESSION = 57;
  public int JJTPLSQLEXPRESSIONLIST = 58;
  public int JJTPLSQLINCLAUSE = 59;
  public int JJTPLSQLBETWEENCLAUSE = 60;
  public int JJTPLSQLLIKECLAUSE = 61;
  public int JJTISNULLCLAUSE = 62;
  public int JJTPLSQLSIMPLEEXPRESSION = 63;
  public int JJTPLSQLMULTIPLICATIVEEXPRESSION = 64;
  public int JJTPLSQLEXPOTENTEXPRESSION = 65;
  public int JJTPLSQLUNARYEXPRESSION = 66;
  public int JJTPLSQLPRIMARYEXPRESSION = 67;
  public int JJTTABLECOLUMN = 68;
  public int JJTORACLEOBJECTNAME = 69;
  public int JJTRELOP = 70;
  public int JJTTABLEREFERENCE = 71;
  public int JJTPARAMETERLIST = 72;
  public int JJTNUMORID = 73;
  public int JJTPARAMETER = 74;
  public int JJTARGUMENTS = 75;
  public int JJTSELECTSTATEMENT = 76;
  public int JJTSELECTWITHOUTORDER = 77;
  public int JJTSELECTLIST = 78;
  public int JJTSELECTITEM = 79;
  public int JJTINTOCLAUSE = 80;
  public int JJTINTOITEM = 81;
  public int JJTFROMCLAUSE = 82;
  public int JJTFROMITEM = 83;
  public int JJTWHERECLAUSE = 84;
  public int JJTCONNECTCLAUSE = 85;
  public int JJTGROUPBYCLAUSE = 86;
  public int JJTSETCLAUSE = 87;
  public int JJTORDERBYCLAUSE = 88;
  public int JJTFORUPDATECLAUSE = 89;
  public int JJTSQLEXPRESSION = 90;
  public int JJTSQLANDEXPRESSION = 91;
  public int JJTSQLUNARYLOGICALEXPRESSION = 92;
  public int JJTEXISTSCLAUSE = 93;
  public int JJTSQLRELATIONALEXPRESSION = 94;
  public int JJTSQLEXPRESSIONLIST = 95;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 96;
  public int JJTSQLINCLAUSE = 97;
  public int JJTSQLBETWEENCLAUSE = 98;
  public int JJTSQLLIKECLAUSE = 99;
  public int JJTSQLSIMPLEEXPRESSION = 100;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 101;
  public int JJTSQLEXPOTENTEXPRESSION = 102;
  public int JJTSQLUNARYEXPRESSION = 103;
  public int JJTSQLPRIMARYEXPRESSION = 104;
  public int JJTFUNCTIONCALL = 105;
  public int JJTSQLARGUMENTS = 106;
  public int JJTOUTERJOINEXPRESSION = 107;
  public int JJTSUBQUERY = 108;


  public String[] jjtNodeName = {
    "Start",
    "getCompilationUnits",
    "getCompilationUnit",
    "DeclarationSection",
    "Declarations",
    "IdentifierDeclaration",
    "CursorDeclaration",
    "ProcedureDeclaration",
    "ProcedureBody",
    "FunctionDeclaration",
    "FunctionBody",
    "PragmaDeclaration",
    "VariableDeclaration",
    "ConstantDeclaration",
    "TypeDeclaration",
    "BasicDataTypeDeclaration",
    "ExceptionDeclaration",
    "BeginEndBlock",
    "SequenceOfStatements",
    "ExceptionBlock",
    "ExceptionHandler",
    "PLSQLStatement",
    "LabelDeclaration",
    "SQLStatement",
    "SubroutineCall",
    "AssignmentStatement",
    "ExitStatement",
    "GotoStatement",
    "IfStatement",
    "LoopStatement",
    "NormalLoop",
    "WhileLoop",
    "ForLoop",
    "NumericForLoopLookahead",
    "NumericForLoop",
    "CursorForLoop",
    "NullStatement",
    "RaiseStatement",
    "ReturnStatement",
    "CloseStatement",
    "CommitStatement",
    "FetchStatement",
    "LockTableStatement",
    "OpenStatement",
    "RollbackStatement",
    "SetTransactionStatement",
    "LockMode",
    "SavepointStatement",
    "UpdateStatement",
    "ColumnValues",
    "UpdatedValue",
    "InsertStatement",
    "DeleteStatement",
    "QueryStatement",
    "PlSqlExpression",
    "PlSqlAndExpression",
    "PlSqlUnaryLogicalExpression",
    "PlSqlRelationalExpression",
    "PlSqlExpressionList",
    "PlSqlInClause",
    "PlSqlBetweenClause",
    "PlSqlLikeClause",
    "IsNullClause",
    "PlSqlSimpleExpression",
    "PlSqlMultiplicativeExpression",
    "PlSqlExpotentExpression",
    "PlSqlUnaryExpression",
    "PlSqlPrimaryExpression",
    "TableColumn",
    "OracleObjectName",
    "Relop",
    "TableReference",
    "ParameterList",
    "NumOrID",
    "Parameter",
    "Arguments",
    "SelectStatement",
    "SelectWithoutOrder",
    "SelectList",
    "SelectItem",
    "IntoClause",
    "IntoItem",
    "FromClause",
    "FromItem",
    "WhereClause",
    "ConnectClause",
    "GroupByClause",
    "SetClause",
    "OrderByClause",
    "ForUpdateClause",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLExpotentExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "FunctionCall",
    "SQLArguments",
    "OuterJoinExpression",
    "SubQuery",
  };
}
/* JavaCC - OriginalChecksum=12f4a190e7fe027818e2e2d0beb70d93 (do not edit this line) */
