//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.12 at 11:40:08 AM EST 
//


package com.oracle.xmlns.forms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.converter.toolkit.ui.FormsObject;


/**
 * <p>Java class for Module complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Module">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}FormModule"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}ObjectLibrary"/>
 *         &lt;element ref="{http://xmlns.oracle.com/Forms}MenuModule"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Module", namespace = "http://xmlns.oracle.com/Forms", propOrder = {
    "formModule",
    "objectLibrary",
    "menuModule"
})
@XmlRootElement(name = "Module")
public class Module
    extends FormsObject
{

    @XmlElement(name = "FormModule", namespace = "http://xmlns.oracle.com/Forms")
    protected FormModule formModule;
    @XmlElement(name = "ObjectLibrary", namespace = "http://xmlns.oracle.com/Forms")
    protected ObjectLibrary objectLibrary;
    @XmlElement(name = "MenuModule", namespace = "http://xmlns.oracle.com/Forms")
    protected MenuModule menuModule;
    @XmlAttribute
    protected Long version;

    /**
     * Gets the value of the formModule property.
     * 
     * @return
     *     possible object is
     *     {@link FormModule }
     *     
     */
    public FormModule getFormModule() {
        return formModule;
    }

    /**
     * Sets the value of the formModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormModule }
     *     
     */
    public void setFormModule(FormModule value) {
        this.formModule = value;
    }

    /**
     * Gets the value of the objectLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectLibrary }
     *     
     */
    public ObjectLibrary getObjectLibrary() {
        return objectLibrary;
    }

    /**
     * Sets the value of the objectLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectLibrary }
     *     
     */
    public void setObjectLibrary(ObjectLibrary value) {
        this.objectLibrary = value;
    }

    /**
     * Gets the value of the menuModule property.
     * 
     * @return
     *     possible object is
     *     {@link MenuModule }
     *     
     */
    public MenuModule getMenuModule() {
        return menuModule;
    }

    /**
     * Sets the value of the menuModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenuModule }
     *     
     */
    public void setMenuModule(MenuModule value) {
        this.menuModule = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

}
