//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 10:16:46 PM IST 
//


package com.release3.javasql;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.release3.javasql package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.release3.javasql
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link R3JavaSqlGen }
     * 
     */
    public R3JavaSqlGen createR3JavaSqlGen() {
        return new R3JavaSqlGen();
    }

    /**
     * Create an instance of {@link JavaPlSqlType }
     * 
     */
    public JavaPlSqlType createJavaPlSqlType() {
        return new JavaPlSqlType();
    }

}
