/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package com.release3.jj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_PROCEDURE = 6;
  /** RegularExpression Id. */
  int K_BEGIN = 7;
  /** RegularExpression Id. */
  int WORD = 8;
  /** RegularExpression Id. */
  int UNDERSCORE_IDENTIFIER = 9;
  /** RegularExpression Id. */
  int OBRACE = 10;
  /** RegularExpression Id. */
  int CBRACE = 11;
  /** RegularExpression Id. */
  int K_IS = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\t\"",
    "\"PROCEDURE\"",
    "\"BEGIN\"",
    "<WORD>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"IS\"",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
