/*******************************************************************************
 * Copyright (c) 2009, 2013 ObanSoft Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Jayansh Shinde
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.28 at 07:27:29 PM IST 
//


package com.release3.r3builtin.builtinlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuiltinsMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuiltinsMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JavaEquivalentBuiltin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CrudEquivalentBuiltin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FormBuiltin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuiltinsMap", propOrder = {
    "javaEquivalentBuiltin",
    "crudEquivalentBuiltin"
})
public class BuiltinsMap {

    @XmlElement(name = "JavaEquivalentBuiltin")
    protected String javaEquivalentBuiltin;
    @XmlElement(name = "CrudEquivalentBuiltin")
    protected String crudEquivalentBuiltin;
    @XmlAttribute(name = "FormBuiltin")
    protected String formBuiltin;

    /**
     * Gets the value of the javaEquivalentBuiltin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaEquivalentBuiltin() {
        return javaEquivalentBuiltin;
    }

    /**
     * Sets the value of the javaEquivalentBuiltin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaEquivalentBuiltin(String value) {
        this.javaEquivalentBuiltin = value;
    }

    /**
     * Gets the value of the crudEquivalentBuiltin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudEquivalentBuiltin() {
        return crudEquivalentBuiltin;
    }

    /**
     * Sets the value of the crudEquivalentBuiltin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudEquivalentBuiltin(String value) {
        this.crudEquivalentBuiltin = value;
    }

    /**
     * Gets the value of the formBuiltin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormBuiltin() {
        return formBuiltin;
    }

    /**
     * Sets the value of the formBuiltin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormBuiltin(String value) {
        this.formBuiltin = value;
    }

}
