//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.28 at 07:27:29 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.release3.com/R3Builtin/builtinlist", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.release3.r3builtin.builtinlist;
