//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 10:16:46 PM IST 
//


package com.release3.plsqlgen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.oracle.xmlns.forms.ProgramUnit;
import com.oracle.xmlns.forms.Trigger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="R3Trigger" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Trigger" type="{http://xmlns.oracle.com/Forms}Trigger"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ItemName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProgramUnit" type="{http://xmlns.oracle.com/Forms}ProgramUnit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FormName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "r3Trigger",
    "programUnit"
})
@XmlRootElement(name = "R3PlSql")
public class R3PlSql {

    @XmlElement(name = "R3Trigger")
    protected List<R3PlSql.R3Trigger> r3Trigger;
    @XmlElement(name = "ProgramUnit")
    protected List<ProgramUnit> programUnit;
    @XmlAttribute(name = "FormName")
    protected String formName;

    /**
     * Gets the value of the r3Trigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the r3Trigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getR3Trigger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link R3PlSql.R3Trigger }
     * 
     * 
     */
    public List<R3PlSql.R3Trigger> getR3Trigger() {
        if (r3Trigger == null) {
            r3Trigger = new ArrayList<R3PlSql.R3Trigger>();
        }
        return this.r3Trigger;
    }

    /**
     * Gets the value of the programUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the programUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgramUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProgramUnit }
     * 
     * 
     */
    public List<ProgramUnit> getProgramUnit() {
        if (programUnit == null) {
            programUnit = new ArrayList<ProgramUnit>();
        }
        return this.programUnit;
    }

    /**
     * Gets the value of the formName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormName() {
        return formName;
    }

    /**
     * Sets the value of the formName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormName(String value) {
        this.formName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Trigger" type="{http://xmlns.oracle.com/Forms}Trigger"/>
     *       &lt;/sequence>
     *       &lt;attribute name="BlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ItemName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trigger"
    })
    public static class R3Trigger {

        @XmlElement(name = "Trigger", required = true)
        protected Trigger trigger;
        @XmlAttribute(name = "BlockName")
        protected String blockName;
        @XmlAttribute(name = "ItemName")
        protected String itemName;
        @XmlAttribute(name = "Name")
        protected String name;

        /**
         * Gets the value of the trigger property.
         * 
         * @return
         *     possible object is
         *     {@link Trigger }
         *     
         */
        public Trigger getTrigger() {
            return trigger;
        }

        /**
         * Sets the value of the trigger property.
         * 
         * @param value
         *     allowed object is
         *     {@link Trigger }
         *     
         */
        public void setTrigger(Trigger value) {
            this.trigger = value;
        }

        /**
         * Gets the value of the blockName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlockName() {
            return blockName;
        }

        /**
         * Sets the value of the blockName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlockName(String value) {
            this.blockName = value;
        }

        /**
         * Gets the value of the itemName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemName() {
            return itemName;
        }

        /**
         * Sets the value of the itemName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemName(String value) {
            this.itemName = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
