//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 08:57:51 PM IST 
//


package com.release3.plsqlgen;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.release3.customization.RefreshType;
import com.release3.customization.builtin.BuiltinType;
import com.release3.customization.parameter.ParameterType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Trigger" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Parameter" type="{http://www.release3.com/plsqlgen}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Refresh" type="{http://www.release3.com/plsqlgen}RefreshType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Block" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Item" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Jsfattr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="plsql" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MethodType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Builtin" type="{http://www.release3.com/plsqlgen}BuiltinType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * using R3.java instead of R3PreCustomization 
 */
@Deprecated
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trigger",
    "builtin"
})
@XmlRootElement(name = "R3PreCustomization")
public class R3PreCustomization {

    @XmlElement(name = "Trigger")
    protected List<R3PreCustomization.Trigger> trigger;
    @XmlElement(name = "Builtin", required = true)
    protected BuiltinType builtin;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the trigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrigger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link R3PreCustomization.Trigger }
     * 
     * 
     */
    public List<R3PreCustomization.Trigger> getTrigger() {
        if (trigger == null) {
            trigger = new ArrayList<R3PreCustomization.Trigger>();
        }
        return this.trigger;
    }

    /**
     * Gets the value of the builtin property.
     * 
     * @return
     *     possible object is
     *     {@link BuiltinType }
     *     
     */
    public BuiltinType getBuiltin() {
        return builtin;
    }

    /**
     * Sets the value of the builtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuiltinType }
     *     
     */
    public void setBuiltin(BuiltinType value) {
        this.builtin = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Parameter" type="{http://www.release3.com/plsqlgen}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Refresh" type="{http://www.release3.com/plsqlgen}RefreshType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Block" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Item" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Jsfattr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="plsql" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MethodType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter",
        "refresh"
    })
    public static class Trigger {

        @XmlElement(name = "Parameter")
        protected List<ParameterType> parameter;
        @XmlElement(name = "Refresh")
        protected List<RefreshType> refresh;
        @XmlAttribute(name = "Block")
        protected String block;
        @XmlAttribute(name = "Item")
        protected String item;
        @XmlAttribute(name = "Jsfattr")
        protected String jsfattr;
        @XmlAttribute(name = "plsql")
        protected String plsql;
        @XmlAttribute(name = "MethodType")
        protected String methodType;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParameterType }
         * 
         * 
         */
        public List<ParameterType> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<ParameterType>();
            }
            return this.parameter;
        }

        /**
         * Gets the value of the refresh property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the refresh property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRefresh().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RefreshType }
         * 
         * 
         */
        public List<RefreshType> getRefresh() {
            if (refresh == null) {
                refresh = new ArrayList<RefreshType>();
            }
            return this.refresh;
        }

        /**
         * Gets the value of the block property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlock() {
            return block;
        }

        /**
         * Sets the value of the block property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlock(String value) {
            this.block = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the jsfattr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJsfattr() {
            return jsfattr;
        }

        /**
         * Sets the value of the jsfattr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJsfattr(String value) {
            this.jsfattr = value;
        }

        /**
         * Gets the value of the plsql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlsql() {
            return plsql;
        }

        /**
         * Sets the value of the plsql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlsql(String value) {
            this.plsql = value;
        }

        /**
         * Gets the value of the methodType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMethodType() {
            return methodType;
        }

        /**
         * Sets the value of the methodType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMethodType(String value) {
            this.methodType = value;
        }

    }

}
