//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.05 at 10:07:58 PM IST 
//


package com.release3.customization.parameter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Block" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Item" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ViewPortForm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ViewPort" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Canvas" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Formname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterType")
public class ParameterType {

    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Block")
    protected String block;
    @XmlAttribute(name = "Item")
    protected String item;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "ViewPortForm")
    protected String viewPortForm;
    @XmlAttribute(name = "ViewPort")
    protected String viewPort;
    @XmlAttribute(name = "Canvas")
    protected String canvas;
    @XmlAttribute(name = "Formname")
    protected String formname;
    @XmlAttribute(name = "Selected")
    protected Boolean selected;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the block property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlock() {
        return block;
    }

    /**
     * Sets the value of the block property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlock(String value) {
        this.block = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItem(String value) {
        this.item = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the viewPortForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewPortForm() {
        return viewPortForm;
    }

    /**
     * Sets the value of the viewPortForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewPortForm(String value) {
        this.viewPortForm = value;
    }

    /**
     * Gets the value of the viewPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewPort() {
        return viewPort;
    }

    /**
     * Sets the value of the viewPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewPort(String value) {
        this.viewPort = value;
    }

    /**
     * Gets the value of the canvas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvas() {
        return canvas;
    }

    /**
     * Sets the value of the canvas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvas(String value) {
        this.canvas = value;
    }

    /**
     * Gets the value of the formname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormname() {
        return formname;
    }

    /**
     * Sets the value of the formname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormname(String value) {
        this.formname = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

}
