//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 07:48:33 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.release3.com/SpecialChars", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.release3.specialchars;
