//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 07:48:33 AM IST 
//


package com.release3.specialchars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialCharsReplacer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialCharsReplacer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specialChar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="replacement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialCharsReplacer", propOrder = {
    "specialChar",
    "replacement"
})
public class SpecialCharsReplacer {

    @XmlElement(required = true)
    protected String specialChar;
    @XmlElement(required = true)
    protected String replacement;

    /**
     * Gets the value of the specialChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialChar() {
        return specialChar;
    }

    /**
     * Sets the value of the specialChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialChar(String value) {
        this.specialChar = value;
    }

    /**
     * Gets the value of the replacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacement() {
        return replacement;
    }

    /**
     * Sets the value of the replacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacement(String value) {
        this.replacement = value;
    }

}
