/*******************************************************************************
 * Copyright (c) 2009, 2013 ObanSoft Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Jayansh Shinde
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.17 at 11:21:34 AM IST 
//


package com.release3.r3coreplsqlgen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.release3.customization.builtin.BuiltinType;


/**
 * <p>Java class for R3CorePlSql complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="R3CorePlSql">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PlSqlText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Builtin" type="{http://www.release3.com/Customization/Builtin}BuiltinType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PlSqlName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PlSqlDefinition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BlockName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ItemName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toBeMigrate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="MoveToDB" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "R3CorePlSql", propOrder = {
    "plSqlText",
    "builtin"
})
public class R3CorePlSql {

    @XmlElement(name = "PlSqlText")
    protected String plSqlText;
    @XmlElement(name = "Builtin")
    protected List<BuiltinType> builtin;
    @XmlAttribute(name = "PlSqlName")
    protected String plSqlName;
    @XmlAttribute(name = "PlSqlDefinition")
    protected String plSqlDefinition;
    @XmlAttribute(name = "BlockName")
    protected String blockName;
    @XmlAttribute(name = "ItemName")
    protected String itemName;
    @XmlAttribute(name = "toBeMigrate")
    protected Boolean toBeMigrate;
    @XmlAttribute(name = "MoveToDB")
    protected Boolean moveToDB;

    /**
     * Gets the value of the plSqlText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlSqlText() {
        return plSqlText;
    }

    /**
     * Sets the value of the plSqlText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlSqlText(String value) {
        this.plSqlText = value;
    }

    /**
     * Gets the value of the builtin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the builtin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuiltin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuiltinType }
     * 
     * 
     */
    public List<BuiltinType> getBuiltin() {
        if (builtin == null) {
            builtin = new ArrayList<BuiltinType>();
        }
        return this.builtin;
    }

    /**
     * Gets the value of the plSqlName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlSqlName() {
        return plSqlName;
    }

    /**
     * Sets the value of the plSqlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlSqlName(String value) {
        this.plSqlName = value;
    }

    /**
     * Gets the value of the plSqlDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlSqlDefinition() {
        return plSqlDefinition;
    }

    /**
     * Sets the value of the plSqlDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlSqlDefinition(String value) {
        this.plSqlDefinition = value;
    }

    /**
     * Gets the value of the blockName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockName() {
        return blockName;
    }

    /**
     * Sets the value of the blockName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockName(String value) {
        this.blockName = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemName(String value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the toBeMigrate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isToBeMigrate() {
        if (toBeMigrate == null) {
            return false;
        } else {
            return toBeMigrate;
        }
    }

    /**
     * Sets the value of the toBeMigrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToBeMigrate(Boolean value) {
        this.toBeMigrate = value;
    }

    /**
     * Gets the value of the moveToDB property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMoveToDB() {
        if (moveToDB == null) {
            return true;
        } else {
            return moveToDB;
        }
    }

    /**
     * Sets the value of the moveToDB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMoveToDB(Boolean value) {
        this.moveToDB = value;
    }

}
